# DON'T FORGET TO RUN gulp build:process before deploying
application: eventsandppl
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /css
  static_dir: dist/css

- url: /js
  static_dir: dist/js

- url: /html
  static_dir: dist/views

- url: /img
  static_dir: static/img

- url: /
  static_files: dist/index.html
  upload: dist/index\.html
  secure: always

- url: /_ah/spi/.*
  script: main.api
  secure: always

libraries:
- name: endpoints
  version: latest
- name: pycrypto
  version: latest